### PR TITLE
Fix broken dashboard save

### LINKED ISSUE #1909: Saving on close from control panel does not save most recent changes
To reproduce:
1. Create new notebook
2. Create new cell, type something
3. Open control panel in different tab
4. Close the session of the notebook you created from the control panel tab
5. Accept to save changes, save to some file
6. Open file, see that the cell you created is missing

### PR DESCRIPTION
**Pull request by samccone**
Fixes #1909

### CODE REVIEW

**Comment by scottdraves** [comment]
I am getting the new copy of the notebook, but the file has not been pretty printed, and multiline cells have not been broken into arrays of lines.

**Comment by samccone** [comment]
:+1: will fix

File: core/src/main/web/app/controlpanel/controlpanelsessionitem-directive.js [hunk 1]
```diff
@@ -25,6 +25,33 @@
...
+        .catch(deferred.reject);
+
+        $.cometd.unsubscribe('/latest-notebook-model');
+      });
+
+      $.cometd.publish('/request-latest-notebook-model', {sessionId: sessionId});
+
+      return deferred.promise;
+    }
+
```
Comment (DiegoAlbertoTorres) [inline core/src/main/web/app/controlpanel/controlpanelsessionitem-directive.js:54]: Why not move the save to bkNotebookManager?

Comment (samccone) [inline core/src/main/web/app/controlpanel/controlpanelsessionitem-directive.js:54]: I approached this problem with the general assumption that the controlpanel has responsibility for saving the notebook. The reason for this approach was because the controlpanel has the responsibility over handing errors, issuing the final close command to all open notebook sessions, and providing feedback to the user about the operation.

If we were to change where the execution (save) was happening we would be essentially creating an RPC approach across windows / tabs.

Is this what we want?
